<a href="https://colab.research.google.com/github/italolima04/monitoria-probabilidade-estatistica/blob/master/Pesquisa-PID/Implementa%C3%A7%C3%A3o-Algoritmos/Apresenta%C3%A7%C3%A3o_PID_Implementa%C3%A7%C3%A3o.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importando Bibliotecas, Módulos e Dados

In [14]:
import pandas as pd
import numpy as np
import nltk
nltk.download('stopwords')
import re
from sklearn.feature_extraction.text import CountVectorizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [15]:
#Criando Data Frame a partir dos dados.
data = pd.read_csv('dados-pesquisa.csv')

# Visualizando e Explorando Dados

In [16]:
#Visualizando as 5 primeiras linhas.
data.head()

Unnamed: 0                      created_at  ...  user lang
0           0  Mon May 18 17:53:01 +0000 2020  ...   NaN   pt
1           1  Mon May 18 17:52:17 +0000 2020  ...   NaN   pt
2           2  Mon May 18 17:50:40 +0000 2020  ...   NaN   pt
3           3  Mon May 18 17:49:17 +0000 2020  ...   NaN   pt
4           4  Mon May 18 17:49:06 +0000 2020  ...   NaN   pt

[5 rows x 6 columns]

In [17]:
#Visualizando as 5 últimas linhas.
data.tail()

Unnamed: 0  ... lang
109959      109959  ...   pt
109960      109960  ...   pt
109961      109961  ...   pt
109962      109962  ...   pt
109963      109963  ...   pt

[5 rows x 6 columns]

In [18]:
#Verificando a estrutura inicial dos dados.
data.shape

(109964, 6)

**Podemos observar aproximadamente 110 mil linhas e 6 colunas.**

# Tratando os Dados

In [19]:
#Removendo dados duplicados na coluna de Texto e substituindo dentro do próprio Data Frame.
data.drop_duplicates(['text'], inplace=True)

In [20]:
#Verificando novamente a estrutura dos dados para observar a quantidade de dados únicos.
data.shape

(103364, 6)

6600 linhas foram removidas.

**Iremos trabalhar com os Dados de Texto, por isso, selecionaremos apenas a coluna associada ao conteúdo dos tweets.**

In [21]:
#Utilizando notação comum em estudos de Aprendizado de Máquina.
X = data['text']

In [22]:
#Visualizando as 15 primeiras linhas. 
X[:15]

0     Tudo mudou na nossa forma de trabalhar, mas na...
1     McDonald’s já reabriu lojas ao público https:/...
2     Sindicato, está atento em tudo o que envolve s...
3     Nossos problemas da saúde definitivamente acab...
4     Fábricas de todo o mundo se viram obrigadas a ...
5     @g1 @RedeGlobo @jornalhoje o governo de @jairb...
6     Lei N° 6666, nos #EUA, que pretende traçar e i...
7     https://t.co/mcftUwJr5F o governo precisa ser ...
8     Blockchain: a tecnologia que popularizou o #bi...
9     VOCÊS CONHECEM ALGUM PAÍS ALÉM DO BRASIL QUE T...
10    Itajuípe recebe o Centro Municipal de Isolamen...
11    📣 NOTÍCIA / NEWS / NOUVELLES \n\n🇵🇹 Manual de ...
12    Enquanto o governo Bolsonaro permanecer Irresp...
13    Faça a diferença! Seja um doador sem fronteira...
14    Manaus, maio de 2020. Reportagem sobre o colap...
Name: text, dtype: object

**Devido ao fato de os dados serem proveninentes de uma rede social, se faz necessária uma etapa de pré-processamento nos mesmos.**

In [23]:
def Preprocessing_data(instance):
      instance = re.sub(r"http\S+", "", instance).lower().replace('.', '').replace(';','').replace('-','').replace(':', '').replace(')', '')
      stopwords = set(nltk.corpus.stopwords.words('portuguese'))
      words = [i for i in instance.split() if not i in stopwords]
      return (" ".join(words))

**Função que remove links, urls, sinais de pontuação, padroniza os caracteres como minúsculos e remove as stopwords através de um dos módulos da biblioteca NLTK.**

In [24]:
#Aplicando a função na nossa base de dados.
X = [Preprocessing_data(i) for i in X]

In [25]:
#Visualizando novamente as 15 primeiras linhas, agora após o pré-processamento.
X[:15]

['tudo mudou forma trabalhar, nada mudou objetivo informar #jornalismo #imprensa…',
 'mcdonald’s reabriu lojas público #comida #covid19 #mcdonalds',
 'sindicato, atento tudo envolve saúde condições trabalho nessa pandemia #covid @spbancarios',
 'problemas saúde definitivamente acabaram #saude #forabolsonaro #covid',
 'fábricas todo mundo viram obrigadas dispensarem funcionários decorrência #covid19 antes m…',
 '@g1 @redeglobo @jornalhoje governo @jairbolsonaro vai socorrer ninguém vai enrolar! pois minto quer r…',
 'lei n° 6666, #eua, pretende traçar investigar percurso pessoas tivestes contatos, usand…',
 'governo precisa ser responsabilizado #covid #covid19',
 'blockchain tecnologia popularizou #bitcoin sendo testada combate #covid19 sistema capaz de…',
 'conhecem algum país além brasil torcida organizada coronavirus???? #covid #covid19',
 'itajuípe recebe centro municipal isolamento covid19 #covid19 #isolamentosocial #covid @rctitajuipe',
 '📣 notícia / news / nouvelles 🇵🇹 manual boa

# Aplicando Tokenização e Vetorização nos Dados de Texto 

**Iremos agora Tokenizar e depois Vetorizar esses dados de Texto, tornando-os uma matriz numérica.**


In [26]:
#A partir da biblioteca Keras instanciando o Tokenizer e definindo que serão utilizada as 20000 palavras mais comuns. 
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=20000)

Using TensorFlow backend.


In [27]:
#Aplicando a Tokenização nos dados.
tokenizer.fit_on_texts(X)

In [28]:
sequences = tokenizer.texts_to_sequences(X)

**É atribuído um número para cada palavra encontrada na base de dados.**

In [29]:
#As frases agora são constituídas por uma sequência numérica.
sequences[:15]

[[49, 1692, 424, 478, 105, 1692, 908, 2352, 2631, 4130],
 [5261, 940, 342, 2506, 2],
 [2134, 4316, 49, 6256, 16, 1212, 181, 327, 7, 14],
 [840, 16, 1474, 4317, 1426, 1075, 14],
 [17414, 51, 24, 3222, 13445, 850, 1213, 2, 95, 343],
 [130, 3154, 5800, 30, 126, 11, 8887, 276, 11, 297, 15121, 112, 1054],
 [482, 6026, 93, 4131, 13446, 2170, 17415, 19, 7120],
 [30, 309, 22, 7510, 14, 2],
 [1523, 4426, 156, 914, 39, 2, 313, 810, 146],
 [7121, 757, 54, 392, 6, 1891, 3844, 4, 14, 2],
 [714, 490, 486, 99, 2, 2, 4824, 14],
 [12036,
  236,
  265,
  13447,
  10182,
  1116,
  4672,
  249,
  2553,
  549,
  15122,
  8348,
  7511,
  2553,
  159],
 [195, 30, 21, 6027, 2469, 107, 1671, 113, 686],
 [567, 1427, 2507, 7122, 14, 2, 13448, 6],
 [1428, 537, 53, 994, 13, 748, 1023, 164, 399, 62, 219, 212, 98, 452]]

Observando acima o novo formato para as 15 primeiras linhas.

In [30]:
#Importando Módulo do Keras.
from keras import preprocessing

**Precisamos transformar esses dados em uma Matriz 2D.**

In [31]:
#Tornando-os uma matriz através de um método do módulo preprocessing.
sequences = preprocessing.sequence.pad_sequences(sequences)

In [32]:
#Visualizando o novo formato para as 15 primeiras linhas.
sequences[:15]

array([[    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,    49,  1692,   424,   478,   105,  1692,   908,  2352,
         2631,  4130],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,  5261,   940,   342,
         2506,     2],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,  2134,  4316,    49,  6256,    16,  1212,   181,   327,
            7,    14],
       [    0,     0,     0,     0,     0,     0,     0,     0,     0,
        

# Aplicando Algoritmos

In [33]:
#Importando algoritmo KMeans da biblioteca Sklearn.
from sklearn.cluster import KMeans

In [34]:
#Instanciando objeto kmeans, definindo o número de clusters e definindo a quantidade máxima de iterações.
kmeans = KMeans(n_clusters=3, init='k-means++', max_iter=100, n_init=1)

In [36]:
#Treinando o Modelo.
kmeans.fit(sequences)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
       n_clusters=3, n_init=1, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [37]:
#Verificando labels originados.
kmeans.labels_

array([1, 1, 1, ..., 1, 1, 2], dtype=int32)

In [38]:
#Criando uma nova coluna no Data Frame. Associando cada tweet ao seu respectivo agrupamento feito pelo algoritmo.
data['Kclasses'] = kmeans.labels_

In [39]:
#Visualizando tipos únicos para a coluna.
data['Kclasses'].unique()

array([1, 2, 0], dtype=int32)

In [40]:
#Criando novo Data Frame com as colunas de interesse para visualização. O contéudo do Tweet (text) e o respectivo agrupamento.
df = data [['text', 'Kclasses']]

In [41]:
#Visualizando as 5 primeiras linhas do Data Frame.
df.head()

text  Kclasses
0  Tudo mudou na nossa forma de trabalhar, mas na...         1
1  McDonald’s já reabriu lojas ao público https:/...         1
2  Sindicato, está atento em tudo o que envolve s...         1
3  Nossos problemas da saúde definitivamente acab...         1
4  Fábricas de todo o mundo se viram obrigadas a ...         2

In [42]:
  df['Kclasses'].value_counts()

1    63064
2    24370
0    15930
Name: Kclasses, dtype: int64

In [43]:
#Visualizando tweets agrupados na Classe 0, originada a partir do algoritmo.
classe_0 = df.loc[df.Kclasses == 0,]
classe_0.head(10)

text  Kclasses
22  Hotelaria da Galiza quer que portugueses façam...         0
23  Qual é o tamanho do grupo de risco para #covid...         0
28  Cara se você deseja ter estabilidade financeir...         0
30  #12emPonto98: saiba tudo sobre o pagamento da ...         0
37  Maioria da população não tem anticorpos contra...         0
42  Idosa cadeirante ganha festa de 82 dentro de c...         0
45  Não se preocupe com seus pensamentos durante a...         0
46  #Covid-19 diminui estoque de leite materno no ...         0
50  #covid #coronavírus\n\nPor um lado, os nazista...         0
63  @NataliaBTeles @MmipexRenata @DFDanielFreitas ...         0

In [44]:
#Visualizando tweets agrupados na Classe 1, originada a partir do algoritmo.
classe_1 = df.loc[df.Kclasses == 1,]
classe_1.head(10)

text  Kclasses
0   Tudo mudou na nossa forma de trabalhar, mas na...         1
1   McDonald’s já reabriu lojas ao público https:/...         1
2   Sindicato, está atento em tudo o que envolve s...         1
3   Nossos problemas da saúde definitivamente acab...         1
7   https://t.co/mcftUwJr5F o governo precisa ser ...         1
8   Blockchain: a tecnologia que popularizou o #bi...         1
9   VOCÊS CONHECEM ALGUM PAÍS ALÉM DO BRASIL QUE T...         1
10  Itajuípe recebe o Centro Municipal de Isolamen...         1
12  Enquanto o governo Bolsonaro permanecer Irresp...         1
14  Manaus, maio de 2020. Reportagem sobre o colap...         1

In [45]:
#Visualizando tweets agrupados na Classe 0, originada a partir do algoritmo.
classe_2 = df.loc[df.Kclasses == 2,]
classe_2.head(10)

text  Kclasses
4   Fábricas de todo o mundo se viram obrigadas a ...         2
5   @g1 @RedeGlobo @jornalhoje o governo de @jairb...         2
6   Lei N° 6666, nos #EUA, que pretende traçar e i...         2
11  📣 NOTÍCIA / NEWS / NOUVELLES \n\n🇵🇹 Manual de ...         2
13  Faça a diferença! Seja um doador sem fronteira...         2
16  #covid #coronavírus \nAgrava-se o problema da ...         2
18  Médico alerta para os riscos da hipertensão ar...         2
20  A melhor lembrança do @Flamengo na #Libertador...         2
29  Esqueça seu passado, se perdoe e recomece.) \n...         2
32  Conheça as melhores práticas para a prevenção ...         2

# Aplicando algoritmos com o modelo TF-IDF

**Primeiramente, iremos "resetar" o X, atribuindo-o novamente aos dados da coluna text**

In [47]:
#Utilizando notação comum em estudos de Aprendizado de Máquina.
X = data['text']

In [48]:
#Visualizando as 15 primeiras linhas. 
X[:15]

0     Tudo mudou na nossa forma de trabalhar, mas na...
1     McDonald’s já reabriu lojas ao público https:/...
2     Sindicato, está atento em tudo o que envolve s...
3     Nossos problemas da saúde definitivamente acab...
4     Fábricas de todo o mundo se viram obrigadas a ...
5     @g1 @RedeGlobo @jornalhoje o governo de @jairb...
6     Lei N° 6666, nos #EUA, que pretende traçar e i...
7     https://t.co/mcftUwJr5F o governo precisa ser ...
8     Blockchain: a tecnologia que popularizou o #bi...
9     VOCÊS CONHECEM ALGUM PAÍS ALÉM DO BRASIL QUE T...
10    Itajuípe recebe o Centro Municipal de Isolamen...
11    📣 NOTÍCIA / NEWS / NOUVELLES \n\n🇵🇹 Manual de ...
12    Enquanto o governo Bolsonaro permanecer Irresp...
13    Faça a diferença! Seja um doador sem fronteira...
14    Manaus, maio de 2020. Reportagem sobre o colap...
Name: text, dtype: object

In [49]:
def Preprocessing_data(instance):
      instance = re.sub(r"http\S+", "", instance).lower().replace('.', '').replace(';','').replace('-','').replace(':', '').replace(')', '')
      stopwords = set(nltk.corpus.stopwords.words('portuguese'))
      words = [i for i in instance.split() if not i in stopwords]
      return (" ".join(words))

In [50]:
#Aplicando a função na nossa base de dados.
X = [Preprocessing_data(i) for i in X]

In [51]:
#Visualizando novamente as 15 primeiras linhas, agora após o pré-processamento.
X[:15]

['tudo mudou forma trabalhar, nada mudou objetivo informar #jornalismo #imprensa…',
 'mcdonald’s reabriu lojas público #comida #covid19 #mcdonalds',
 'sindicato, atento tudo envolve saúde condições trabalho nessa pandemia #covid @spbancarios',
 'problemas saúde definitivamente acabaram #saude #forabolsonaro #covid',
 'fábricas todo mundo viram obrigadas dispensarem funcionários decorrência #covid19 antes m…',
 '@g1 @redeglobo @jornalhoje governo @jairbolsonaro vai socorrer ninguém vai enrolar! pois minto quer r…',
 'lei n° 6666, #eua, pretende traçar investigar percurso pessoas tivestes contatos, usand…',
 'governo precisa ser responsabilizado #covid #covid19',
 'blockchain tecnologia popularizou #bitcoin sendo testada combate #covid19 sistema capaz de…',
 'conhecem algum país além brasil torcida organizada coronavirus???? #covid #covid19',
 'itajuípe recebe centro municipal isolamento covid19 #covid19 #isolamentosocial #covid @rctitajuipe',
 '📣 notícia / news / nouvelles 🇵🇹 manual boa

In [52]:
#Importando módulo que contém o modelo, da biblioteca Sklearn.
from sklearn.feature_extraction.text import TfidfVectorizer

In [53]:
#Criando instância do Modelo.
vectorizer = TfidfVectorizer()

In [54]:
#Aplicando modelo nos dados.
X = vectorizer.fit_transform(X)

In [55]:
#Visualizando instância criada.
X

<103364x78504 sparse matrix of type '<class 'numpy.float64'>'
	with 998982 stored elements in Compressed Sparse Row format>

In [56]:
#Importando algoritmo KMeans da biblioteca Sklearn.
from sklearn.cluster import KMeans

In [70]:
#Instanciando objeto kmeans, definindo o número de clusters e definindo a quantidade máxima de iterações.
true_k = 3
kmeans = KMeans(n_clusters=true_k, init='k-means++', max_iter=100, n_init=1)

In [71]:
#Treinando o Modelo.
kmeans.fit(X)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=100,
       n_clusters=3, n_init=1, n_jobs=None, precompute_distances='auto',
       random_state=None, tol=0.0001, verbose=0)

In [72]:
#Verificando labels originados.
kmeans.labels_

array([0, 0, 0, ..., 1, 1, 1], dtype=int32)

In [73]:
#Criando uma nova coluna no Data Frame. Associando cada tweet ao seu respectivo agrupamento feito pelo algoritmo.
data['Kclasses'] = kmeans.labels_

In [74]:
#Visualizando tipos únicos para a coluna.
data['Kclasses'].unique()

array([0, 2, 1], dtype=int32)

In [75]:
#Criando novo Data Frame com as colunas de interesse para visualização. O contéudo do Tweet (text) e o respectivo agrupamento.
df = data [['text', 'Kclasses']]

In [76]:
#Visualizando as 5 primeiras linhas do Data Frame.
df.head()

text  Kclasses
0  Tudo mudou na nossa forma de trabalhar, mas na...         0
1  McDonald’s já reabriu lojas ao público https:/...         0
2  Sindicato, está atento em tudo o que envolve s...         0
3  Nossos problemas da saúde definitivamente acab...         0
4  Fábricas de todo o mundo se viram obrigadas a ...         0

In [77]:
  df['Kclasses'].value_counts()

0    80988
1    12046
2    10330
Name: Kclasses, dtype: int64

In [78]:
#Visualizando tweets agrupados na Classe 0, originada a partir do algoritmo.
classe_0 = df.loc[df.Kclasses == 0,]
classe_0.head(10)

text  Kclasses
0  Tudo mudou na nossa forma de trabalhar, mas na...         0
1  McDonald’s já reabriu lojas ao público https:/...         0
2  Sindicato, está atento em tudo o que envolve s...         0
3  Nossos problemas da saúde definitivamente acab...         0
4  Fábricas de todo o mundo se viram obrigadas a ...         0
5  @g1 @RedeGlobo @jornalhoje o governo de @jairb...         0
6  Lei N° 6666, nos #EUA, que pretende traçar e i...         0
7  https://t.co/mcftUwJr5F o governo precisa ser ...         0
8  Blockchain: a tecnologia que popularizou o #bi...         0
9  VOCÊS CONHECEM ALGUM PAÍS ALÉM DO BRASIL QUE T...         0

In [79]:
#Visualizando tweets agrupados na Classe 1, originada a partir do algoritmo.
classe_1 = df.loc[df.Kclasses == 1,]
classe_1.head(10)

text  Kclasses
115  Tocantins decreta lockdown após reabrir comérc...         1
118  Dilemas e alternativas em tempos de Covid-19 h...         1
125  #saopaulo #COVID19 #COVIDー19  #lockdown #rushh...         1
233  O TERROR DO LOCKDOWN E AS ESTRATÉGIAS DOS GOVE...         1
298  Covas diz que saúde de SP está perto do colaps...         1
350  Sobre a #Covid no Brasil 😷 🦠\n.\n📌 #SP continu...         1
444  Um covarde, assassino, criminoso.\n#impeachmen...         1
463  Supermercados em Wuhan na. 2ª quinzena de jane...         1
847  Amanhã o  Estado de Pernambuco estará em lockd...         1
867  Notícias do dia! #lockdown prorrogado no Pará!...         1

In [80]:
#Visualizando tweets agrupados na Classe 0, originada a partir do algoritmo.
classe_2 = df.loc[df.Kclasses == 2,]
classe_2.head(10)

text  Kclasses
24   Articulação dos Povos Indígenas do Brasil - AP...         2
27   Rapaziada fiquem espertos! Existem umas minas ...         2
55   Atualização #COVID19 Mundo\n\nAtualização: 18/...         2
97   Já passa de 1,5 milhão o número de recuperados...         2
111  Rio de Janeiro tem 2,7 mil mortes por covid-19...         2
113  Covid-19: Concelho da Maia volta a ter casos d...         2
130  A Comunidade Intermunicipal (CIM) Região de Co...         2
132  Atualização #COVID19 Mundo\n\nAtualização: 18/...         2
141  Comunidade cigana em Barcelos sem novos casos ...         2
165  O #Brasil atinge 16.118 mortes por #Coronavíru...         2

**Iremos agora verificar a divisão dos principais termos entre as classes.**

In [81]:
centroids = kmeans.cluster_centers_.argsort()[:, ::-1]
terms = vectorizer.get_feature_names()

In [86]:
for i in range(true_k):
    print("Cluster %d:" % i),
    for ind in centroids[i, :10]:
      print(' %s' % terms[ind])

Cluster 0:
 coronavírus
 covid19
 coronavirus
 contra
 pandemia
 novo
 vacina
 sobre
 pra
 bolsonaro
Cluster 1:
 lockdown
 vai
 pra
 ter
 aqui
 curitiba
 dias
 tá
 cidade
 goiás
Cluster 2:
 casos
 mortes
 brasil
 covid19
 coronavírus
 mil
 novos
 confirmados
 registra
 óbitos
